// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {history} from '../models';

export function Cancel():Promise<void>;

export function CheckTools():Promise<main.ToolStatus>;

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function ListHistory():Promise<Array<history.Summary>>;

export function LoadHistory(arg1:Array<number>):Promise<Array<history.Entry>>;

export function SaveHistory(arg1:main.HistorySaveRequest):Promise<number>;

export function Scan(arg1:main.ScanRequest):Promise<void>;

export function ScanPorts(arg1:main.PortScanRequest):Promise<void>;

export function Trace(arg1:main.TraceRequest):Promise<void>;

export function TraceTargets(arg1:main.TraceTargetsRequest):Promise<void>;
