// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckTools() {
  return window['go']['main']['App']['CheckTools']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function LoadHistory(arg1) {
  return window['go']['main']['App']['LoadHistory'](arg1);
}

export function NetClose(arg1) {
  return window['go']['main']['App']['NetClose'](arg1);
}

export function NetConnect(arg1) {
  return window['go']['main']['App']['NetConnect'](arg1);
}

export function NetSend(arg1, arg2) {
  return window['go']['main']['App']['NetSend'](arg1, arg2);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function ScanPorts(arg1) {
  return window['go']['main']['App']['ScanPorts'](arg1);
}

export function Trace(arg1) {
  return window['go']['main']['App']['Trace'](arg1);
}

export function TraceTargets(arg1) {
  return window['go']['main']['App']['TraceTargets'](arg1);
}
